### ISSUE TITLE
Opuka unable to access key in windows registry

### ISSUE THREAD

**Issue by RandomMan25XX** [XorTroll/CiaGenerate#1]
anytime I try to convert dsiware for the 3ds the tool will simply open up and say "Opuka was unable to access Opuka's key in Windows Registry. Exiting current process" any clue why it's doing that?

**Comment by DeadSkullzJr** [comment]
I can confirm, I have the same issue.

**Comment by XorTroll** [comment]
Yes. The problem is that this executable was made using some libraries from another project I have, which is Opuka, so it doesn't work sometimes. I'm going to try to fix it.

**Comment by XorTroll** [comment]
OK, now I've remade it, so I think it doesn't give that error now.
