### ISSUE TITLE
Blank CIAs Generated

### ISSUE THREAD

**Issue by RandomMan25XX** [XorTroll/CiaGenerate#2]
Now I've either used the tool incorrectly (That's probably it), but after generating CIAs from some iQue DSiWare roms only blank CIAs were generated

**Comment by XorTroll** [comment]
RandomMan25XX, I must tell you that the building system for DSiWare is still experimental. I'm fixing some issues for beta 4 right now, and I've remade DSiWare building system. Now, it should work with even single DS ROMs. I'll publish it in a few days.
